### ISSUE TITLE
How to construct URI given IDs?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#1]
In the document 'PUAM_data.docx' there are guidelines for assigning object and image URIs, which is great. I was wondering if there are similar instructions on how to construct URIs for other entities, such as:
Constituent
Exhibition
Reference
Media
Term

Of which the IDs are given in the data.

**Comment by cathryng** [comment]
artmuseum.princeton.edu/person
artmuseum.princeton.edu/exhibition
artmuseum.princeton.edu/bibliography
artmuseum.princeton.edu/media
artmuseum.princeton.edu/terms

**Comment by VladimirAlexiev** [comment]
Please use /thesaurus (or /concept) instead of /term.
And if you have the concept type, add that to the URL, eg /thesaurus/material/123 vs /thesaurus/subject/456.

**Comment by cathryng** [comment]
at present we can just do these - 
artmuseum.princeton.edu/collections/terms/<termid>
artmuseum.princeton.edu/collections/objects/<objectid>
artmuseum.princeton.edu/collections/maker/<constituentid>
artimage.princeton.edu/files/ProductionJpegs/<filename>
