### ISSUE TITLE
Image Links

### ISSUE THREAD

**Issue by azaroth42** [american-art/PUAM#10]
The images in the media have names ... but no URIs at which they're resolvable. There must be a mapping possible, but it doesn't seem to be present in the results.  Access to image content for applications would be useful.

**Comment by cathryng** [comment]
Yes,  the data was pulled before we had loris up and running. It's being tested and so we will need to upload images and provide a new Json file for media

Sent from my iPhone

On Jun 28, 2016, at 7:41 PM, Rob Sanderson <notifications@github.com<mailto:notifications@github.com>> wrote:

The images in the media have names ... but no URIs at which they're resolvable. There must be a mapping possible, but it doesn't seem to be present in the results. Access to image content for applications would be useful.

**Comment by cathryng** [comment]
new path for images:  artimage.princeton.edu/files/ProductionJpegs/filename - no IIIF availability yet
