### ISSUE TITLE
Are the date fields in apibibliography_american about publication?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#2]
There are three dates column in this file: displayDate, beginDate, and endDate. Is this information about the publication?

**Comment by cathryng** [comment]
Yes, all date of publication – begindate and enddate are sortdates – displaydate is a display field.

**Comment by VladimirAlexiev** [comment]
See https://github.com/american-art/PUAM/issues/6 for an image of the best way to map them (display->P3, start/end->P82a/b)
