### ISSUE TITLE
apiconstituents_american

### ISSUE THREAD

**Issue by steads** [american-art/PUAM#21]
There is no data to validate the mapping with. 
The mapping to E39 Actor makes the mapping rather weak as the use of the superclass restricts the utility of the resulting data.
The birth dates of instances of E21 Person should be mapped as:-
E21 ->P98i ->E67 ->P4 ->E52     ->P82 ->E61
                ->P78  ->E50
P98 may not be used with E39.
The date of death of instances of E21 Person should be mapped as:-
E21 ->P100i ->E69 ->P4 ->E52    ->P82 ->E61
                ->P78  ->E50
P100 may not be used with E39.
The P129i ->E33 ->P3 ->E62 construct for ConstituentPositionURI is probably incorrect. Use:-
E39(E21/E40)    ->P3 ->E62
        ->P3.1  -> E55 Type {Constituent Position URI}
The P129i ->E33 ->P3 ->E62 construct for Biography is probably incorrect. Use:-
E39(E21/E40)    ->P3 ->E62
        ->P3.1  -> E55 Type {Biography}
Nationality should use P107 has current or former member (is current or former member of) not PX_nationality (which does not exist).
The use of E82 Actor Appellation is unlikely to be correct. Use:-
E39 ->P1 ->E41
The use of P106 is composed of (forms part of) to decompose the appellations into constituent parts is correct.
However caution is called for as many constituent parts of names in art museum catalogues are not Appellations but descriptions of group membership. 
Groups may need to be separated from individuals and then the true meaning of component parts and the relationships to each other and the instance of E39 Actor can then be assessed.
The use of P2 ->E55 from each of the appelations is impossible to verify without access to the data.

**Comment by cathryng** [comment]
role data is found in the objconxrefs data - the named entity may have different roles in different works. primary roles to be concerned with art Artist (used for most makers) Culture (used for unnamed artists) and person depicted
