### ISSUE TITLE
media_american

### ISSUE THREAD

**Issue by steads** [american-art/PUAM#23]
There is no data to validate the mapping with. 
The P129i ->E33 ->P3 ->E62 construct for Copyright is probably incorrect. Use:-
E38 ->P3 ->E62
    ->P3.1  -> E55 Type {Copyright}
I would normally expect Copyright to be mapped as E30 Right. 
CopyrightInfoURI cannot be assessed without examples.
It seems unusual for AltImageURI to be linked using P48 has preferred identifier (is preferred identifier of).
Filenames are rarely titles so I am cautious of the use of E35 Title.

**Comment by cathryng** [comment]
new data uploaded for this - includes copyright statements and copyright status when restricted.
path for images should be "artimage.princeton.edu/files/ProductionJpegs/filename"
