### ISSUE TITLE
apiconaltnames

### ISSUE THREAD

**Issue by steads** [american-art/PUAM#25]
There is no data to validate the mapping with. 
The P129i ->E33 ->P3 ->E62 construct for Position is probably incorrect. Use:-
E38 ->P3 ->E62
    ->P3.1  -> E55 Type {Position}
The use of E82 Actor Appellation is unlikely to be correct. Use:-
E39 ->P1 ->E41
The use of P106 is composed of (forms part of) to decompose the appellations into constituent parts is correct.
However caution is called for as many constituent parts of names in art museum catalogues are not Appellations but descriptions of group membership. 
Groups may need to be separated from individuals and then the true meaning of component parts and the relationships to each other and the instance of E39 Actor can then be assessed.
The use of P2 ->E55 from each of the appelations is impossible to verify without access to the data.

**Comment by VladimirAlexiev** [comment]
There is now data, please update from Github.

It's probably best to get rid of name parts as suggested by @edgartdata at https://github.com/american-art/npg/issues/39. Eg consider:

``` turtle
<http://americanartcollaborative.org/puam/person-institution/6338/appellation> a crm:E82_Actor_Appellation ;
    rdfs:label "Caylus Painter" ;
    crm:P106_is_composed_of <http://americanartcollaborative.org/puam/person-institution/6338/appellation/lastname> ;
    crm:P2_has_type <http://americanartcollaborative.org/puam/thesauri/nametype/primary-name> .

<http://americanartcollaborative.org/puam/person-institution/6338/appellation/lastname> a crm:E82_Actor_Appellation ;
    rdfs:label "Caylus Painter" ;
    crm:P2_has_type <http://americanartcollaborative.org/puam/thesauri/nametype/last-name> .
```
1. It's pointless to say P106_is_composed_of a single part.
2. That's an unknown Attic painter [ulan:500017060](http://www.getty.edu/vow/ULANFullDisplay?find=Caylus+Painter&role=&nation=&prev_page=1&subjectid=500017060) so talking about his (her?) last name is incorrect

ULAN doesn't have name parts, and the first/last name distinction is very Western-centric

**Comment by cathryng** [comment]
these names are variants for the primary name associated with the constituent id - links to ulan will compensate for this so perhaps we don't need it here

**Comment by VladimirAlexiev** [comment]
@edgartdata suggested we skip name parts, @steads suggested we keep them (if someone wants to do some research on eg last names).
But the first/last name distinction is Western-centric, and breaks down in many cases.

**Comment by VladimirAlexiev** [comment]
@cathryng where is the PUAM data so I can validate?
- Searching for the value "6338" doesn't find anything from your museum: http://yasgui.org/short/Skqa3gPDb
- github doesn't have apiconaltnames anymore, but apiconstituents_american.json includes FirstName, MiddleName, LastName, etc

> these names are variants for the primary name
- this issue is not about alt names but about ignoring name parts. @edgartdata do you agree, or we are happy to keep them?
- The name parts are mapped with P106_is_composed_of (see 5 links of that name in apiconstituents_american-model.pdf)
