### ISSUE TITLE
apibibaltnums

### ISSUE THREAD

**Issue by steads** [american-art/PUAM#26]
There is no data to validate the mapping with. 
I am cautious of the use E31 Document as bibliographies rarely only contain scientific documentation. 
Verification is required that the AltNum data actually constitutes instances of E75 Conceptual Object Appellation. They may just be E41 Appellation, in which case use P1 not P149

**Comment by cathryng** [comment]
this data is links to worldcat or isbn numbers for publications.  if it's not useful let's leave it out - possibly needs to be made more consistent on our end
