### ISSUE TITLE
apiconuris

### ISSUE THREAD

**Issue by steads** [american-art/PUAM#27]
There is no data to validate the mapping with. 
The use of E82 Actor Appellation is unlikely to be correct. Use:-
E39 ->P1 ->E41

**Comment by VladimirAlexiev** [comment]
There is data since 23 March, please update from Github.
The modeling is very broken:

``` turtle
<http://americanartcollaborative.org/puam/person-institution/89> a crm:E39_Actor ;
    crm:P131_is_identified_by <http://americanartcollaborative.org/puam/person-institution/89/appellation> .
<http://americanartcollaborative.org/puam/person-institution/89/appellation> a crm:E82_Actor_Appellation ;
    rdfs:label "500065743",
        "http://viaf.org/viaf/23519414" ;
    crm:P2_has_type <http://americanartcollaborative.org/puam/thesauri/URIType/ULAN>,
        <http://americanartcollaborative.org/puam/thesauri/URIType/VIAF> .
```
1. This mixes several appellations together.
2. Those are not appellations but identifiers (as Steve says above)
3. Whenever LOD URLs exist, they should be used directly.

So this should become:

``` turtle
<http://americanartcollaborative.org/puam/person-institution/89>
  owl:sameAs
    <http://vocab.getty.edu/ulan/500065743-actor>,
    <http://viaf.org/viaf/23519414>.
```

**Comment by cathryng** [comment]
yes

**Comment by VladimirAlexiev** [comment]
https://github.com/american-art/PUAM/issues/44, https://github.com/american-art/PUAM/issues/45
