### ISSUE TITLE
uploaded data - 12 days ago

### ISSUE THREAD

**Issue by cathryng** [american-art/PUAM#29]
were my new data files properly received and integrated? media and mediaxrefs.  Also dropboxed terms data to Craig - was that received?
cathryn

**Comment by kateblanch** [comment]
Hi Cathryn, I don't see new data (the last activity was May 31). I'd be happy to upload files for you, somehow, miraculously I have upload file rights in the repo. 
@caknoblock  -- let me know if you see a problem with that. Thanks!

**Comment by cathryng** [comment]
i think it's there now - the remaining file shared via dropbox with kate and craig - too big to upload

**Comment by caknoblock** [comment]
I don’t see the shared dropbox.  Did you try zip’ing the file and uploading the zip file instead?

**Comment by cathryng** [comment]
https://www.dropbox.com/s/laknow6k6pwj304/apiObjtermsxrefs.json?dl=0

**Comment by cathryng** [comment]
is this ok now or no?  i'll zip the larger file tomorrow if neither kate or craig has been able to get it from dropbox.  what about the other two?  to me it looks like they uploaded just fine.  media and mediaxrefs

**Comment by caknoblock** [comment]
I prefer if people learn how to put their own files into github.  Moving files for 14 different organizations can become very time consuming.  I have not moved it.

**Comment by cathryng** [comment]
All of the data files from Princeton are uploaded to github.  3 new files.
media_american.json
apiobjmediaxrefs.json
apiobjtermsxrefs.json
