### ISSUE TITLE
Dimension units are strings, not entities

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#31]
For example, on http://data.americanartcollaborative.org/page/puam/object/10012/dimension/342695

the unit is "Centemeters", however they're required to be a E58 Measurement Unit.  Preferably we'd use http://www.qudt.org/ so that we have convertible, calculable units, but at the very least it should be an entity.

**Comment by workergnome** [comment]
This is closer now, but the units now don't have labels.

**Comment by bsnikhila** [comment]
Yes, that happened by mistake. It will be rectified next time the triples are uploaded to the triple store.

**Comment by workergnome** [comment]
Still not fixed:  http://data.americanartcollaborative.org/page/puam/centimeters

**Comment by bsnikhila** [comment]
Fixed it.
http://data.americanartcollaborative.org/page/puam/thesauri/measurement_unit/centimeters
