### ISSUE TITLE
Multiple Dimensions of the same type for a given object

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#32]
If you look at, say, http://data.americanartcollaborative.org/page/puam/object/10012 there are five dimensions given.  

Two of these are widths, and two are heights.  I would assume that there's an entity involved somehow:  some are with frames and some are not, but I can't tell that from the provided data.

Height: 87.8 centimeters
Width: 48.9 centimeters
Height: 76.2 centimeters
Width: 61 centimeters
Depth: 3 centimeters

@cathryng, do you have any insight here?

**Comment by cathryng** [comment]
Hi David - the dimension element is in the data - but seems to have been dropped from the mapping:

"DimensionID":53175,
"DimItemElemXrefID":26734,
"ObjectID":40926,
**"Element":"sheet",**
"ElementRank":1,
"ElemDescription":null,
"DimensionType":"Height",
"DimRank":1,
"Dimension":25.2,
"DimUnit":"centimeters"

**Comment by workergnome** [comment]
Thanks, @cathryng.

In that case, these dimensions should be modeled using the ["in parts" dimension model](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_19-search_0).   It's fine to be consistent here and use that for everything, even if there's only one part.

**Comment by workergnome** [comment]
Looking at the data today, these appear to be modeled _almost_ correctly.  The only thing missing is a label for the individual parts.  For instance, http://data.americanartcollaborative.org/page/puam/object/10012/Overall should have a label "Overall".

**Comment by bsnikhila** [comment]
Modified it to include the label.
http://data.americanartcollaborative.org/page/puam/object/10012/overall
