### ISSUE TITLE
Nationalities are unique per-individual.

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#33]
http://data.americanartcollaborative.org/puam/constituent/6443/group is "American", but http://data.americanartcollaborative.org/puam/constituent/6447/group is also "American".  

Nationalities should pull from a global thesaurus.  Preferably cross-AAC, but at least within an institution each nationality should have a single URI.

**Comment by bsnikhila** [comment]
Fixed it.
http://data.americanartcollaborative.org/page/puam/thesauri/nationality/american
