### ISSUE TITLE
comments from AAC workbench review of mappings

### ISSUE THREAD

**Issue by cathryng** [american-art/PUAM#35]
Review of AAC Metadata Mapping

Sample size: 30 objects from American Art Department, ranging from core- to fully- cataloged records, tested using David Newbury’s AAC mapping verification tool.

Record Elements that Consistently Queried Properly: Primary Title, Artist*, Credit Line, Classification, Medium (text), Dimension (display), Dimension (elements), Object ID.

Record Elements that Failed to Query Properly: Alternate title, Creation Date, Creation Location, Acquisition Date, Descriptions, Style/Subject/Technique/Concept, Material Terms (backend), Owner, Current Location, (Part) Dimensions, Rights Info., Preferred ID, Accession Number, Alternate IDs, Websites, Images, Cat Raisonne and Edition Notes.

Notes:
Alternative title: doesn’t pull based on titleType:Alternative designation, rather based on whether the “display” box is checked, regardless of “type”. For instance, in x1991-38 (ID: 18062), there are primary, group, and full titles.  Clicking “alternative title” in the tool will pull the full title, as this is the only one besides primary that has “display” checked. 

Artists: Pulls, but in cases where there are multiple constituents (eg. An “artist” and “person depicted”), all are returned without qualification (all undifferentiated as crm:E39_Actor).  Also, this may just be an anomaly, but for one object tested (PP169 / ID: 45162), the tool returned the “depicted” constituent but not the artist.  The only way I can see that this record differs from most with “depicted” constituents is that the “displayed” box is not checked for “depicted” here.  I don’t know why that would matter but displayed/not-displayed seems to be playing some tricks in the data.

**Comment by workergnome** [comment]
Catherine, of the elements that didn't query, are there any that are not included in your data export?  For instance, are you providing  information about Catalog Raisonnes?

**Comment by cathryng** [comment]
Record Elements that Failed to Query Properly: Alternate title, Creation Date, Creation Location, **Acquisition Date**, Descriptions, Style/Subject/Technique/Concept, **Material Terms** (backend), Owner, Current Location, (Part) Dimensions, Rights Info., **Preferred ID, Accession Number, Alternate IDs,** Websites, Images, Cat Raisonne and Edition Notes.

**Comment by cathryng** [comment]
of the highlighted fields above Acquisition Date is inferred from the accession number - first part is the year.  Material terms do not exist in the data. PreferredID, Accession Number should be objectid and objectnumber in the data. Alternate IDs - not sure what this would be.  All the other data fields are in our data.

**Comment by workergnome** [comment]
Alternate IDs are IDs that are not accession number, preferred ID, or any other ID we've explicitly modeled.  (For instance, CMOA has a GUID associated with each entity for internal tracking, and someone else mentioned an ID from a previous CMS.)

**Comment by cathryng** [comment]
mapping has been resolved - no catalogue raisonne or edition mappings were done as we understand
