### ISSUE TITLE
Date Ranges don't have labels

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#37]
For entities with timespans that are ranges, there is no rdfs:label for the period.

see: http://data.americanartcollaborative.org/page/puam/object/10079/production/timespan

It's interesting, because ones that are *not* ranges, do:

http://data.americanartcollaborative.org/page/puam/object/10015/production/timespan

**Comment by bsnikhila** [comment]
There is a column Dated given in the data file. If this value is Null, there is no rdfs:label for the period. If it is not null, whatever value is provided is emitted as the rdfs:label.

**Comment by workergnome** [comment]
Makes sense.  Better to represent the data as is than construct things, I suppose.
