### ISSUE TITLE
Thesaurus for culture group in apiconaltnames?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#4]
Is there thesaurus for culture group at PUAM? If yes then what does a typical URI look like?

**Comment by VladimirAlexiev** [comment]
I don't know the answer to this question, but if possible it would be great to connect them to AAT.
AAT has the Periods and Styles facet (5.5k), and part of that is Nationalities (which are also connected to ULAN)

**Comment by cathryng** [comment]
Cultures are in our data as constituent records AND as Culture Terms.  Culture terms are linked to the AAT - possibly we should only map this and not the constituent ID when Culture terms exist.

**Comment by YinyiUSC** [comment]
I think we could still do both. Cultures could be mapped as an attribute of constituents, while its URI might come from AAT.

**Comment by VladimirAlexiev** [comment]
I think @cathryng points out a different thing: PUAM got _constituent_ records for Cultures, considered as groups of people.
ULAN has a similar thing, eg:
- http://vocab.getty.edu/ulan/500355202 is "Bulgarian",
- http://vocab.getty.edu/ulan/500355202-agent is a group (schema:Organization), 
- it has nationality http://vocab.getty.edu/aat/300111163 "Bulgarian (culture or style)"

If PUAM doesn't have additional cultures, it's best to use the ULAN/AAT URLs directly.

In CRM you represent this as

``` Turtle
<constituent> a crm:E21_Person;
  crm:P107i_is_current_or_former_member_of <nationality>.
<nationality> a crm:E74_Group.
```

**Comment by YinyiUSC** [comment]
I mapped Culture as what Vladmir suggested. However the culture URIs haven't been created since I couldn't find a thesauri to link those terms to.

**Comment by VladimirAlexiev** [comment]
AAT Styles and Periods has 5.5k of which 2.5k are nationalities, and the rest other kinds of styles (eg Impressionism). See
http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&subjectid=300264088
