### ISSUE TITLE
PUAM productions without date

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#40]
https://github.com/american-art/npg/issues/71 shows that there are 330 productions without any date info.
This query http://yasgui.org/short/Sy5_hKj2x shows the object and production URLs.
```sparql
SELECT * {
  ?x crm:P52_has_current_owner <http://data.americanartcollaborative.org/puam>;
     crm:P108i_was_produced_by ?prod
  filter not exists {?prod crm:P4_has_time-span ?y}
  filter not exists {?prod rdfs:label ?y}
} 
```
@kateblanch could the PUAM person check whether that is ok, i.e. there are indeed 330 objects with any date info?

**Comment by kateblanch** [comment]
@cathryng  -- 
Some objects (330) have missing production dates (date created). Can you check the source data to see if this is true? If you follow this link, it will list the Object IDs (and their corresponding Production URLs) so you can check the source data. http://yasgui.org/short/Sy5_hKj2x shows the object and production URLs.

**Comment by cathryng** [comment]
that's not too surprising - we do have objects with no dates.  What have you done for others in this situation?  ordinarily we use a date range based on artist life dates, but that's not always possible either.

**Comment by VladimirAlexiev** [comment]
@cathryng Have you checked some of these 330 objects?

**Comment by AndrewDWilk** [comment]
@VladimirAlexiev [I’m in cathryn’s dept. at PUAM] I took a look at the provided list of objects with missing production date info.  Appears that in these cases production date info is missing because we don’t have any production dates for these objects.

**Comment by VladimirAlexiev** [comment]
ok, closing
