### ISSUE TITLE
PUAM constituent dates as xsd:date

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#41]
http://data.americanartcollaborative.org/puam/constituent/93/birth/time
Change to
```ttl
crm:P82a_begin_of_the_begin	"1947-01-01"^^xsd:date;
crm:P82b_end_of_the_end	"1947-12-31"^^xsd:date.
```

**Comment by bsnikhila** [comment]
http://data.americanartcollaborative.org/page/puam/constituent/93/birth/date

Changed to xsd:date.
