### ISSUE TITLE
PUAM constituents with empty birth/death

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#42]
http://data.americanartcollaborative.org/page/puam/constituent/6388/birth
http://data.americanartcollaborative.org/page/puam/constituent/6388/death
have no data at all.

For other constituents I've seen birth/death dates. So if a particular constituent has no birth date (and separately no death date), skip those nodes and the incoming relation.

**Comment by bsnikhila** [comment]
This particular constituent was one of the zombies, and no longer exists. I anyway modified the model to remove nodes where there are no birth/death dates.
