### ISSUE TITLE
PUAM dimension units need label

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#43]
http://data.americanartcollaborative.org/puam/centimeters
add skos:prefLabel "cm" 

Also, would be nice to move these URLs a couple of levels down, eg 
http://data.americanartcollaborative.org/puam/thesaurus/units/centimeters

**Comment by workergnome** [comment]
Or go directly to AAT, and skip the institutional thesaurus all together.

**Comment by bsnikhila** [comment]
Changed it to http://data.americanartcollaborative.org/page/puam/thesauri/measurement_unit/centimeters and added the rdfs:label.
