### ISSUE TITLE
PUAM constituent name part type URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#44]
http://data.americanartcollaborative.org/puam/constituent/89/appellation/middle_name: this URL is per-constituent, which is wasteful. Replace with eg http://data.americanartcollaborative.org/puam/thesaurus/constituent/middle_name

**Comment by bsnikhila** [comment]
Changed the URIs to http://data.americanartcollaborative.org/page/puam/constituent/89/family_name and http://data.americanartcollaborative.org/page/puam/thesauri/name_type/family_name
