### ISSUE TITLE
PUAM constituent ULAN URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#45]
apiconstituents_american.json has this:
```js
"ConstituentID":93,
"DisplayName":"Laurie Anderson",
"Code":"ULAN \/ 500070794",
```
But http://data.americanartcollaborative.org/page/puam/constituent/100 doesn't have an ULAN URL.
Please add one (first check the mapping on "review")

**Comment by cathryng** [comment]
we can add ulan urls where they exist - not all will.  does the fact that we have ulan urls in our data mean that we don't need to do the link curation?  or is it possible to do link curation only on the constituents that don't have ulan urls already?

**Comment by caknoblock** [comment]
We evaluated some of the ULAN data provided by the museums and we found quite a few errors in some of them (I don’t think we evaluated PUAM), so we were going to relink all of the datasets and then compare them with the original data.

**Comment by bsnikhila** [comment]
I have added the ULAN URLs in the mapping.
