### ISSUE TITLE
PUAM birth/death place is missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#46]
[Actor mapping](http://review.americanartcollaborative.org/entity/E39_Actor#field_14-search_0) shows birth/death place mapped through P7_took_place_at.

The Karma mapping model apicongeography-birth-model.pdf shows it, but I haven't seen any, eg
- http://data.americanartcollaborative.org/page/puam/constituent/6388/birth: no place
- http://data.americanartcollaborative.org/page/puam/constituent/89/birth: no place
- http://data.americanartcollaborative.org/page/puam/constituent/6351/birth: no node

@bsnikhila please take a look

**Comment by bsnikhila** [comment]
The birth and death places have been added.
Note: Constituents 6388 and 6351 do not exist.
