### ISSUE TITLE
PUAM zombie constituents

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#47]
(Split from https://github.com/american-art/SAAM/issues/18. Related to #42, #46).
`apicongeography.json`:
```json
"ConGeographyID":1741,
"ConstituentID":6388,
"ConGeoCode":"Birth Place",
"Continent":"Europe",
"Country":"Belarus",
"City":"Viciebsk",

"ConGeographyID":1742,
"ConstituentID":6388,
"ConGeoCode":"Death Place",
"Continent":"Europe",
"Country":"France",
"City":"Saint-Paul-de-Vence",
```
But there is no record with Constituent ID 6388 in the apiconstituents file. 
So this says "there is a person who was born in Viciebsk and died in Saint-Paul-de-Vence, but we're not going to tell you his name".
@kateblanch Can you please ask the PUAM person to take care of this. I could try to cross-ref the two JSON files...

@bsnikhila said: this is why it is appearing as a zombie: http://data.americanartcollaborative.org/puam/constituent/6388.
But by the same logic, how can you explain how http://data.americanartcollaborative.org/puam/constituent/6351 has only type, but no
http://data.americanartcollaborative.org/puam/constituent/6351/birth and death nodes?

**Comment by kateblanch** [comment]
@cathryng - checking in to see if there's a way to double check the contents of your constituents file vs. the objects file? there may be instances where you have constituents listed that are not included in the objects file.

**Comment by VladimirAlexiev** [comment]
CCMA has a similar problem and I extracted some IDs for them: https://github.com/american-art/ccma/issues/25

**Comment by cathryng** [comment]
ah, it is true that i didn't filter all of the sub-data files from constituents for "American"  can we just drop the ones that don't link or do you want me to submit new data sets?  this should also be the case with apiconuri.json i imagine.

**Comment by caknoblock** [comment]
Since we map each data file separately and then link them when they get loaded into the triple store, we don’t have a way to just drop the ones that don’t link.  If David thinks these are a problem, then it would be great if you could submit new datasets with the format of the datasets unchanged.

**Comment by workergnome** [comment]
Well, they're going to show up if they're published, so if we don't want them out there, they're going to need to be filtered out at some stage.

**Comment by cathryng** [comment]
yes - will have this to you tomorrow

**Comment by bsnikhila** [comment]
This seems to be fixed.
