### ISSUE TITLE
PUAM places (production, depicted) are missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#49]
apiobjgeograph_american.json:
```js
"ObjGeographyID":37677,
"ObjectID":35893,
"GeoCode":"Place depicted",
"PrimaryDisplay":1,
"Continent":"North America",
"SubContinent":null,
"Country":"United States",
"Region":null,
"State":"New York",
"City":"New York",
"County":null,
"SubRegion":null,
"Locale":null,
"Locus":null,
"River":null,
"Excavation":null,
"Latitude":"40.71427",
"Longitude":"74.00597",
"GeoNames":"http:\/\/www.geonames.org\/5128581\/new-york-city.html",
```

`"GeoCode":"Place depicted"` means we should find it in http://data.americanartcollaborative.org/page/puam/object/35893 `crm:P62_depicts`, but it's missing.

**Comment by VladimirAlexiev** [comment]
Consider the next record:
```js
"ObjectID":36618,
"GeoCode":"Place made",
```
We should find it in http://data.americanartcollaborative.org/page/puam/object/36618/production `crm:P7_took_place_at`, see [production location mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_5-search_0), but it's missing

**Comment by workergnome** [comment]
In particular, the GeoNames mapping is extremely important—it's a external URI to a authority, and should be treated similarly to how we're treating ULAN references

**Comment by VladimirAlexiev** [comment]
@workergnome please specify how you want the Place info to be laid out, since it's missing in the mapping (as per https://github.com/american-art/aac_mappings/issues/58)

**Comment by workergnome** [comment]
In my preferred system, I'd like

`crm:P7_took_place_at tgn:7007567 .` or `crm:P7_took_place_at genomes:5128581 .`  


(with the usual request that the label and source are included with external references)

I'd also be fine with


```
 crm:P7_took_place_at _:place.
_:place a crm:E53_Place;
  rdfs:label  "New York";
  skos:exactMatch genomes:5128581.
```

Explicit lat/lng, as in http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_5-search_0 could be nice, as well.  

I think that the creation of an institution-specific gazetteer is probably out of scope for this project, so I don't know that capturing the full hierarchy is worth the effort.

**Comment by VladimirAlexiev** [comment]
"Place depicted" should be linked using crm:P62_depicts, 
"Place made" should be linked to Production using crm:P7_took_place_at

**Comment by bsnikhila** [comment]
Added 'depicts' and 'production location'.
