### ISSUE TITLE
Mapping hierarchical geographical information in apicongeography

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#5]
Since there are 12 levels of hierarchy (scope) for geographical information, the model will be huge if we specify each of the fields (This is a screenshot for mapping geo information with four levels https://github.com/usc-isi-i2/saam-lod/blob/master/models-graphviz-screenshot/cbev2.WebConGeography.csv_graphviz_screenshot.png). Is it possible that we take some of the more important fields and map those hierarchically? I could still include the other fields by combining all of them into a bigger string so that we don't leave out any information.

**Comment by caknoblock** [comment]
What are the 12 levels provided by the source?  The four levels in your example here make sense.

**Comment by cathryng** [comment]
Json data looks takes this structure – in American Art it’s rare to have all of these fields present .  but we will often  have Continent, Country, Region, State, City, County, Locale, Latitude, Longitude, Geonames

ObjGeographyID
ObjectID
GeoCode
PrimaryDisplay
Continent
SubContinent
Country
Region
State
City
County
SubRegion
Locale
Locus
River
Excavation
Latitude
Longitude
GeoNames
SysTimeStamp

**Comment by VladimirAlexiev** [comment]
This is a complex topic. Some considerations:
- IMHO it's imperative to make the different levels as different nodes, and connect them with "P88i forms part of"
- if there are plenty of GeoNames ID's maybe it's best to just use the GeoNames URL
- but you need it for all levels (eg Continent, Country)...
- It's better to map those in a step that is separate from Objects

**Comment by caknoblock** [comment]
In the next phase of the project, we plan to link the geographic locations to either TGN or Geonames, so any reasonable mapping of the geographic data should be fine.  If there is a GeoNames ID, we would certainly want that modeled.

**Comment by VladimirAlexiev** [comment]
> If there is a GeoNames ID, we would certainly want that modeled.

You can model this simply by using the Geonames URL.

**Comment by YinyiUSC** [comment]
Would you please show me how to get the Geonames URL for a specific place? For example, if I want to get the URL for Los Angeles, CA, do I simply search for it on http://www.geonames.org/, and use the url of the matching search result? In this case it would be http://www.geonames.org/maps/google_34.052_-118.244.html

**Comment by VladimirAlexiev** [comment]
The semantic URL of LA is http://sws.geonames.org/5368361 where 5368361 is the geonames ID.
Searching manually is not going to be effective. I understand @caknoblock to mean you got Geonames ID; if not you need a geonames lookup/ coref/ reconciliation service

**Comment by caknoblock** [comment]
I don’t know if there are any Geonames Ids in the dataset.  My point was that we do not need to focus on linking to Geonames at this phase of the project.
