### ISSUE TITLE
missing PUAM classifications

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#50]
http://data.americanartcollaborative.org/page/puam/object/17328 has one classification "photographs"
This corresponds to this record from apiobjtermsxrefs_american.json:
```js
"ObjectID":17328,
"ThesXrefType":"Classification",
"TermID":2053200,
"Term":"photographs",
```

But the same object has two more classifications, map them as well:
```js

"ThesXrefType":"Classification",
"TermID":2053728,
"Term":"black-and-white photographs",

"ThesXrefType":"Classification",
"TermID":2154270,
"Term":"black-and-white photography",
```

There is also a Culture:
```js
"ThesXrefType":"Culture",
"TermID":2038492,
"Term":"American",
```
Map it to classification with crm:P21_had_general_purpose aat:300015646 "styles and periods"

**Comment by bsnikhila** [comment]
Added them all.
