### ISSUE TITLE
PUAM units of measurement

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#51]
http://data.americanartcollaborative.org/puam/centimeters has only type:
- add rdfs:label "centimeters"
- better move hte URL a couple levels down: http://data.americanartcollaborative.org/puam/thesauri/unit/centimeters,
to parallel eg http://data.americanartcollaborative.org/puam/thesauri/dimension/width

**Comment by workergnome** [comment]
And if you're doing this, adding a link to AAT centimeters would be very nice.

**Comment by bsnikhila** [comment]
Changed it to http://data.americanartcollaborative.org/page/puam/thesauri/measurement_unit/centimeters and added skos:preflabel.
