### ISSUE TITLE
Accession Number is not mapped.

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#53]
See https://github.com/american-art/aac_mappings/issues/64 for details.

**Comment by bsnikhila** [comment]
There are 3 numbers: Object ID(mapped as Preferred ID), Object Number(mapped as Object No) and Sort Number(mapped as alternate ID). Please let me know if this mapping is right, and which of them should be mapped as Accession Number.

**Comment by AndrewDWilk** [comment]
Those mappings are correct, but when I run our data through the AAC Mapping Validator, I get no results when calling for Preferred ID and I get both the “ObjectID” and “ObjectNumber” when calling for Object ID.  

 “ObjectNumber” in our data should be mapped as accession number.
