### ISSUE TITLE
Rights information is not mapped

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#54]
See https://github.com/american-art/aac_mappings/issues/63—It looks like a revised file wasn't integrated.

**Comment by bsnikhila** [comment]
I can't seem to find the Rights information. I am sorry about it. Could you please tell me which datafile it is in?

**Comment by cathryng** [comment]
https://github.com/american-art/PUAM/blob/master/old_models/media_american/media_american2.json

**Comment by cathryng** [comment]
rights info is kind of moot at this point .... we will not be submitting file paths for restricted images.
