### ISSUE TITLE
Which dates to use in apiconstituents_american

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#6]
There are beginDate, endDate as well as beginDateISO and endDateISO. It seems that the ISO data contain more accurate information since some of the endDate has value '2100' if the artist is still active, while the endDateISO is simply empty in that case. Can I use the ISO dates as the birth and death date for the artists then?

**Comment by cathryng** [comment]
Yes, I think so – in some cases we added a far off date to avoid the empty date field problem we discussed at the meeting in Arkansas – so whichever seems better to you – although I’d say both fields should be the same since they are derived from entry in the same field in TMS…..

**Comment by VladimirAlexiev** [comment]
Please also tack an appropriate XSD type (in this case xsd:date). Eg see this example from Getty:
![exhibitions](https://cloud.githubusercontent.com/assets/536250/14397897/037c30da-fd95-11e5-9eb8-2e9d54827aa9.png)

**Comment by cathryng** [comment]
yes - date fields in apibibliography_american are data of publication

**Comment by YinyiUSC** [comment]
Dates are ambiguous, for example, when '00' is year. Therefore, we are not using xsd:date for this piece of information for now.
