### ISSUE TITLE
Introducing BIBO ontology to better map bibliographical information?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#7]
While CIDOC-CRM does not cover bibliographical information well (a lot of the publication data be mapped as general information), I was wondering if you would like to use BIBO ontology in the models. 

This issue should also be discussed with other museums since we want to keep the mapping consistent (i.e. if we end up using BIBO for PUAM, we'll also use it for other museums)

**Comment by caknoblock** [comment]
What specific information is not covered by CIDOC-CRM?

**Comment by VladimirAlexiev** [comment]
For the Getty vocabs we used BIBO since there's very little bibliographic info.
If there's a lot of info, FRBRoo is the other option

**Comment by caknoblock** [comment]
The conclusion at the Getty meeting the other day was that we could just use the core CIDOC-CRM vocabulary without any extension since our bibliographic entries were very simple.

**Comment by cathryng** [comment]
yes.
