### ISSUE TITLE
Mapping boolean values in apiexhibitions_american

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#8]
I notice that there are several fields with boolean values (0 or 1) such as traveling or inHouse. Would it be okay if I combine those fields into a single field? For example, 

InHouse | Traveling | OnlineHistory | Princeton Public
0            |  1             |  0                    | 0

will be converted to the following string: 

"InHouse: No; Traveling: Yes; OnlineHistory: No; PrincetonPublic: Yes"

And then this string will be assigned as a piece of information about the exhibition

**Comment by cathryng** [comment]
Yes, I think so….

**Comment by cathryng** [comment]
Hi Yinyi  - were you going to try to concatenate these booleans in the mapping?

**Comment by VladimirAlexiev** [comment]
Why do you want to take structured fields and concat them into a string? This contradicts every principle of normalization...

**Comment by VladimirAlexiev** [comment]
@caknoblock 

You want to map them as several P2_has_type on the Exhibition event (just as in https://github.com/american-art/npg/issues/5). 

Eg "traveling exhibition" is aat:300054773. As for the other values, a local AAC thesaurus can be established (what we called "micro-thesauri" at the workshop). Before that, the meaning of each value must be clarified. 

Eg "PrincetonPublic: Yes": does that mean it's public only for Princeton people? or "Princeton" is just an adornment here?

**Comment by cathryng** [comment]
Princeton Public means that the exhibition took place at princeton and is exposed to the public on our website.  this is partly a matter of deciding whether this data is important in the context of AAC.

**Comment by YinyiUSC** [comment]
@VladimirAlexiev Could you please show me how to establish a local AAC thesaurus?

**Comment by VladimirAlexiev** [comment]
``` turtle
@base <http://data.americanartcollaborative.org/>.
<thes/event/exhibition/in-house> a skos:Concept;
  skos:prefLabel "In-house exhibition";
  skos:inScheme <thes/event/>;
  skos:broader aat:300054766. # exhibitions (events)

<thes/event/> a skos:ConceptScheme;
  rdfs:label "Event types".
```

**Comment by VladimirAlexiev** [comment]
@cathryng "took place at princeton" could be mapped to P7_took_place_at, and then the location of Princeton.

But I'd guess it was **organized** by Princeton, which can be mapped as 

``` turtle
<http://artmuseum.princeton.edu/exhibition/123> a crm:E7_Activity;
  P3_has_note "exhibition name";
  P2_has_type aat:300054766; # exhibition
  crm:P14_performed_by ulan:500310237-agent. # Princeton University, Art Museum
```

In JPGM we also model traveling exhibitions thus exhibition-at-venue like this (you may recognize TMS table/field names)
![exhibitions](https://cloud.githubusercontent.com/assets/536250/17323092/4072575c-58a9-11e6-938f-05813fd91ae9.png)

**Comment by cathryng** [comment]
yes - we haven't modeled out our venue data yet.  the flags discussed here are primarily for internal use and can be disregarded i think -
