### ISSUE TITLE
In apiobjects_american, is it correct to say that departments are the owners of the objects?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/PUAM#9]
The question is as stated in the issue title.

**Comment by cathryng** [comment]
Um, no – I think I added a repository field didn’t I?  maybe it fell out in the filtering of American art.  All objects should be owned by Princeton University Art Museum.

Thanks
cathryn

**Comment by VladimirAlexiev** [comment]
This is usually modeled as "has current keeper"

**Comment by YinyiUSC** [comment]
departments are mapped using "has current keeper"
